/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "IP": {                                          "en": "IP",                                              "de": "IP",                                              "ru": "IP",                                              "pt": "IP",                                              "nl": "IP",                                              "fr": "IP",                                              "it": "IP",                                              "es": "IP",                                              "pl": "IZ",                                              "zh-cn": "IP"},
    "PORT": {                                        "en": "PORT",                                            "de": "PORT",                                            "ru": "PORT",                                            "pt": "PORT",                                            "nl": "PORT",                                            "fr": "PORT",                                            "it": "PORT",                                            "es": "PORT",                                            "pl": "Port",                                            "zh-cn": "口"},
    "PASSWORD (leave it empty if not specified)": {"en": "PASSWORD (leave it empty if not specified)", "de": "PASSWORT (leer lassen, wenn nicht anders angegeben)", "ru": "ПАРОЛЬ (оставьте пустым, если не указан)", "pt": "SENHA (deixe em branco se não for especificado)", "nl": "PASSWORD (laat het leeg als dit niet wordt aangegeven)", "fr": "MOT DE PASSE (laissez-le vide si non spécifié)", "it": "PAROLA D'ORDINE (lasciarlo vuoto se non specificato)", "es": "CONTRASEÑA (déjelo vacío si no se especifica)", "pl": "HASŁO (pozostaw puste, jeśli nie podano)", "zh-cn": "密码 （如果没有指定则留空）"},
    "mpd adapter settings": {                        "en": "MPD adapter settings",                            "de": "MPD Adapter Einstellungen",                       "ru": "Настройки драйвера MPD",                          "pt": "Configurações do adaptador MPD",                  "nl": "MPD-adapterinstellingen",                         "fr": "Paramètres de l'adaptateur MPD",                  "it": "Impostazioni dell'adattatore MPD",                "es": "Configuraciones de adaptador MPD",                "pl": "Ustawienia karty sieciowej Мурзя ",               "zh-cn": "钻井设置适配器"},
    "on save adapter restarts with new config immediately": {"en": "on save adapter restarts with new config immediately", "de": "Beim Speichern von Einstellungen der Adapter wird sofort neu gestartet.", "ru": "Сразу после сохранения настроек драйвер перезапуститься с новыми значениями", "pt": "no adaptador de salvar reinicia com nova configuração imediatamente", "nl": "on save-adapter wordt onmiddellijk opnieuw opgestart met nieuwe config", "fr": "sur l'adaptateur de sauvegarde redémarre avec la nouvelle config immédiatement", "it": "su save adapter si riavvia immediatamente con la nuova configurazione", "es": "en el adaptador de guardar se reinicia con nueva configuración de inmediato", "pl": "zapisz ponownym uruchomieniu zasilacza z nowy konfig raz", "zh-cn": "在保存适配器重新启动与新的配置立即"}
};
